name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install Dependencies
              run: npm ci
            - name: Run dev
              run: npm run dev


