name: 06 - Contexts
run-name: My custom workflow run name | ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'


jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Reference: ${{ github.ref }}"
          echo "Sha: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
      - name: Retrieve Variable
        run: |
          echo "The variable is: ${{ vars.my_variable }}"
      - name: Display Environment Variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow variable: $MY_WORKFLOW_VAR"
          echo "Job variable: $MY_JOB_VAR"
          echo "Overwritten variable: $MY_OVERWRITTEN_VAR"
      - name: Display Environment Variables
        run: |
          echo "Workflow variable: $MY_WORKFLOW_VAR"
          echo "Job variable: $MY_JOB_VAR"
          echo "Overwritten variable: $MY_OVERWRITTEN_VAR"


